/* 4. Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed 1000, find the sum of the even-valued terms. */

   public class FibonacciSequence
   {
    public static void Main(string[] args)
    {
        int n1 = 1, n2 = 1, n3, i, number;
        Console.Write("Enter the number of elements: ");
        number = int.Parse(Console.ReadLine());
        Console.Write(n2 + " \n"); //printing from 2    
        for (i = 1; i < number; ++i)    
        {
            n3 = n1 + n2;
            Console.Write(n3 + " \n");
            n1 = n2;
            n2 = n3;
        }
        
        int sum = 0;

        while (n2 <= 1000)
        {
            number = n2 + n1;
            n1 = n2;
            n2 = number;

            if (number % 2 == 0)
            {
                sum += n2;
            }
        }

        Console.WriteLine("The sum of the even-valued terms is: " + sum);
        Console.ReadLine();

    }
   }